// File: NewRace.java

import java.awt.*;
import java.awt.event.*;
import acm.program.*;
import acm.graphics.*;
import acm.util.*;

/**
 * A race program between a hare and a turtle
 */
public class NewRace extends GraphicsProgram{

  private static final int X_STARTLINE   =  28;
  private static final int HARE_X        =   5;
  private static final int HARE_Y        =  20;
  private static final int HARE_SIZE     =  40;
  private static final int CHEETAH_X     =   5;
  private static final int CHEETAH_Y     = 180;
  private static final int CHEETAH_SIZE  =  40;
  private static final int TURTLE_X      =   5;
  private static final int TURTLE_Y      = 100;
  private static final int TURTLE_SIZE   =  40;
  private static final int INSTRUCTION_X = 100;
  private static final int INSTRUCTION_Y =  40;
  
  private int xEndLine;

  private ActiveHare hare;
  private ActiveTurtle turtle;
  private ActiveCheetah cheetah;
  private RandomGenerator rand;
  private int hareSpeed, turtleSpeed, cheetahSpeed;
  private GCanvas canvas;
  private GLabel instructions;

  /**
   * Initialize the canvas
   */
  public void init() {
    canvas   = this.getGCanvas();
    xEndLine = canvas.getWidth() - 70;
    this.addMouseListeners();

    // set racer speeds
    rand = new RandomGenerator();
    hareSpeed   = 2 + rand.nextInt(8); // average of 5.5 for the hare but a wide range.
    turtleSpeed = 4 + rand.nextInt(3); // average of 5 for the turtle but a narrow range.
    cheetahSpeed = 5 + rand.nextInt(5);
    
    int height = canvas.getHeight();
    canvas.add(new GLine(X_STARTLINE, 0, X_STARTLINE, height));
    canvas.add(new GLine(xEndLine, 0, xEndLine, height));

    // display instructions
    this.instructions = new GLabel("Click to begin the race", INSTRUCTION_X, INSTRUCTION_Y);
    this.add(this.instructions);
  }
  
  /**
   * Create and start the racers 
   *
   * @param e the event generated by the mouse click
   */
  public void mouseClicked(MouseEvent e) {
    // Hide the instructions once they've been followed
    this.remove(this.instructions);

    hare   = new ActiveHare(HARE_X, HARE_Y, HARE_SIZE, xEndLine, hareSpeed, canvas);
    turtle = new ActiveTurtle(TURTLE_X, TURTLE_Y, TURTLE_SIZE, xEndLine, turtleSpeed, canvas);
    cheetah = new ActiveCheetah(CHEETAH_X, CHEETAH_Y, CHEETAH_SIZE, xEndLine, cheetahSpeed, canvas);
    hare.start();
    turtle.start();
    cheetah.start();
  }
  
  /**
   * Create a NewRace and start it
   */
  public static void main(String [] args) {
    new NewRace().start();
  }
}
