// Color
import java.awt.Color;

// MouseEvent
import java.awt.event.MouseEvent;

// GraphicsProgram
import acm.program.GraphicsProgram;


/**
 * Class to place a set of boxes on a canvas
 * 
 * @author  J. Andrew Whitford Holey
 * @version November 13, 2013
 */
public class BullseyePlacer2 extends GraphicsProgram
{
  // the number of rows of boxes
  
   // default location of the boxes
  private static final int NUM_BOXES = 10;
  private static final double DEFAULT_X = 100;
  private static final double DEFAULT_Y = 100;
  
  private static final int ODD_NUM = 9;
  private static final int EVEN_NUM = 8;

  // private instance of the SquareBoxes class
  private Bullseye2 bullseye;
  


  /**
   * Create a new set of square boxes on the canvas
   */
  public void init()
  {
    this.addMouseListeners();
    
    Bullseye2 oddBullseye = new Bullseye2(ODD_NUM);
    Bullseye2 evenBullseye = new Bullseye2(EVEN_NUM);
    
    this.add(oddBullseye,DEFAULT_X+150,DEFAULT_Y);
    this.add(evenBullseye,DEFAULT_X,DEFAULT_Y+150);
    
   
    

    //this.bullseye = new Bullseye2(NUM_BOXES);

    //this.add(this.bullseye, DEFAULT_X, DEFAULT_Y);
  }
 

  /**
   * Re-color a box on each mouse click
   * 
   * 
   *
   * @param e the event generated by the mouse click
   */
  public void mouseClicked(MouseEvent e)
  {
    int boxNum = readInt("Enter the box to change color: ", 0, NUM_BOXES-1);
    int red    = readInt("Enter the new red value: ", 0, 255);
    int green  = readInt("Enter the new green value: ", 0, 255);
    int blue   = readInt("Enter the new blue value: ", 0, 255);
   // this.bullseye.setColor(boxNum, new Color(red, green, blue));
  }
 

  /**
   * Create a BoxController and start it
   */
  public static void main(String [] args)
  {
    new BullseyePlacer2().start();
  }
}
